### ISSUE TITLE
Getting Undefined while using Value.Create()

### ISSUE THREAD

**Issue by pavankumarT345** [sinclairzx81/typebox#333] opened 2023-02-28 02:09 UTC
Hi , 
I am importing latest version i.e. **"@sinclair/typebox": "0.25.24".**
I am importing Value in component as 

 **import {Value} from '@sinclair/typebox/value';**
 
  const T = Type.Object({x: Type.Number(), y: Type.Number({default: 42})});
  const A = Value.Create(T); // const A = { x: 0, y: 42 }
  
  console.log('A ==', A);
  
  Getting Error : Undefined is not a function

**Comment by sinclairzx81** [comment] 2023-02-28 02:27
@pavankumarT345 Hi!

Have tested this locally and see the following expected output. This seems ok.

```
A == { x: 0, y: 42 }
```
Could you provide some additional information?

- Bundler: WebPack, ESbuild, Vite, SWC, Rollup or None
- Environment: Node, Deno, Bun or Browser
- Stacktrack: Module, Line Number

**Comment by pavankumarT345** [comment] 2023-02-28 07:20
- Bundler : Metro Bundler for React Native
- Environment: Node
- Stacktrack :  Module : create , Line Number : 161

**Comment by pavankumarT345** [comment] 2023-02-28 07:23
<img width="1728" alt="Screenshot 2023-02-28 at 12 50 36 PM" src="https://user-images.githubusercontent.com/117090207/221782502-ffe23f10-6e0c-44de-bdef-5c334794219d.png">

PFA

**Comment by sinclairzx81** [comment] 2023-02-28 08:50
@pavankumarT345 Hi, 

I'm not familiar with the Metro Bundler for React Native I'm afraid, and I still can't seem to replicate this issue locally. I don't see much in the stack trace you provided to indicate where the problem is (and there's nothing to suggest it would invoke the `Undefined` code path as the schema in the trace is clearly a `number`). So I'm not sure what the issue is, but you can possibly try the following.

1) Compare versions `0.25.23` to `0.25.24` and let me know if one of these works for you. This would help narrow the issue down to the updates that went out on the most recent revision.
2) Check for multiple versions of TypeBox. Note that Jest installs TypeBox as a `devDependency` (and Jest is very common in React codebases), so if you have installed TypeBox as a direct `dependency`, there might be some cross over there. Run `npm ls @sinclair/typebox` and see what it reports.
3) Try flushing out `node_modules` and reinstalling.
4) Try running the following code inside a `index.mjs` file inside of Node. This to rule out a bundler issue.

```typescript
// index.mjs
import { Value } from '@sinclair/typebox/value';
import { Type} from '@sinclair/typebox';

const T = Type.Object({x: Type.Number(), y: Type.Number({default: 42})});
const A = Value.Create(T); // const A = { x: 0, y: 42 }

console.log('A ==', A);
```
```
$ node index.mjs
```
Outside of this, I'm not too sure what else to suggest at this stage. But give the above a try and let me know if any of these help to narrow down where the problem exists.

Keep me posted
S

**Comment by pavankumarT345** [comment] 2023-02-28 10:05
Hi, 
It was working fine with Node .

But, I have tried with both versions 0.25.23 to 0.25.24 but still i am getting same error .

Could you Please clone the repo from your end and run it.
https://github.com/pavankumarT345/TypeBox-Project

**Comment by sinclairzx81** [comment] 2023-02-28 14:04
@pavankumarT345 Heya, I'm not really setup to run remote code on my machine, and don't actually have Java installed, so getting setup this side will be difficult. Also, I'm very unfamiliar with this particular technology stack (so would need detailed instructions on how to use it before attempting to diagnose the issue). 

In saying this, there really shouldn't be any reason why TypeBox is failing on `Value.Create()` (especially as you're able to run it in Node directly), so if I was to have a guess, it's probably one of the following things....

1) The babel / metro react native plugin is failing to transpile correctly.
2) There may be a module conflict between Jest's version of TypeBox and the version of TypeBox you have installed.
3) Something the toolchain is disallowing functions named `export function Undefined(){}` (which is a long shot, but you could test by renaming this function inside `node_modules/@sinclair/typebox/value/create.js`)

### Debugger: Stepping Through

One last thing you can try is `Step Through` / `Step Into` in the debugger looking for the exact call to `Undefined()` that's failing. The `Step Into` should reveal a bit more detail than `Step Over`, The TypeBox code should be very debug-able in this respect, but the places related to value creation you should keep an eye on are the following lines of `create.js`

switch call site: https://github.com/sinclairzx81/typebox/blob/master/src/value/create.ts#L340
the function: https://github.com/sinclairzx81/typebox/blob/master/src/value/create.ts#L246-L252

In all, this problem does appear to be happening outside of TypeBox specifically (and likely somewhere in the transpiler toolchain if I was to have a guess), so there's not really much else I can do to help here I'm afraid. But if you can pinpoint to exactly what in the toolchain might be faulting (maybe running the metro plugin in isolation), or identify something through the debugger.... I'd be happy to another look and review for a solution in TypeBox (if one exists), but at this stage, I'm just not sure what I should be fixing...

I'll leave this issue open for a few days, and happy to discuss more if you can track any additional info.
Keep me posted
S

**Comment by sinclairzx81** [comment] 2023-03-03 08:59
@pavankumarT345 Hey, might close this one off as I get the feeling this issue may relate to the toolchains / transpilers (but expect tracing down the exact issue won't be trivial). Try referencing those two code links in the previous comment and see if you can see the `Undefined()` method transpiled to the JavaScript (the error suggest that `Undefined()` is not a function, which does lead me to believe the transpiler has omitted it somehow, possibly due to the naming of the function, not sure)

Again, Happy to review this if there is something that can be done in TypeBox to help resolve the issue, but without being able to reproduce the issue my side (and with some reluctance to install Java and associated toolchains), there's not too much else I can do....I think the best way to proceed is for you to try and advise what should be done to resolve the issue, but in terms of general usage, TypeBox appears to be fine. 

Will close off this issue for now, happy to re-open if more information comes to light.
All the best!
S

**Closed by sinclairzx81** 2023-03-03 08:59 UTC

**Comment by troZee** [comment] 2025-11-18 10:51
React Native support thread https://github.com/sinclairzx81/typebox/issues/1454
