### ISSUE TITLE
Optimisations to inference in 0.32 seems to cause `ts(2589)` with composite types. 

### ISSUE THREAD

**Issue by Gnuxie** [sinclairzx81/typebox#825] opened 2024-04-10 17:25 UTC
Context: https://github.com/Gnuxie/matrix-protection-suite/pull/26

I hit the limit about [here](https://github.com/Gnuxie/matrix-protection-suite/blob/bfddf00c4adb3336a61ff52bd7bfb44d6698b5c8/src/MatrixTypes/Events.ts#L95) in this file where we make extensive use of composite types to try keep the schema modular. Granted, this could be a misuse of the composite type, and I'm not sure where to go from here. FWIW these Schema were all working as of 0.31.15. 

I couldn't see anything specifically from https://github.com/sinclairzx81/typebox/pull/689 that would be causing this, but I could be missing something.

**Comment by sinclairzx81** [comment] 2024-04-11 08:33
@Gnuxie Hi,

> I couldn't see anything specifically from https://github.com/sinclairzx81/typebox/pull/689 that would be causing this, but I could be missing something.

There has been some recent updates made to Composite to further replicate type evaluation in TypeScript (that is to say, TypeBox is trying to compute the intersection of all types passed to Composite such that the output schema / type is an evaluated `object` type and not a `allOf` representation as would be the case for Intersect). However, the Composite evaluation is an extremely expensive thing to compute, and I think when tagged with `ReturnType` inference (instantiation expressions as per your implementation), this is likely pushing out the extents of the type system.

The recent updates for Composite were to do with Union evaluation. You can read about some of the context here https://github.com/sinclairzx81/typebox/issues/789. I believe these updates went out on 0.32.16, so if you can try 0.32.15 and just let me know if you still see the same issue, I may reinvestigate using the matrix-protection types as a basis for testing.

---

### Workaround

> Granted, this could be a misuse of the composite type, and I'm not sure where to go from here

So, much of the issues here would be to do with TypeBox doing deep type evaluation on the Composite types. If it's reasonable to do so, you can swap from Composite to Intersect. The Intersect type should have the same assertion characteristics as Composite, but the schematics are a bit more "extreme" as each Intersect type is expressed via JSON Schema `allOf` keyword.

Here's a working version of the matrix-protection types using Intersect instead of Composite.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQxsAxgGhezLAEQFMsIATEvAFWSwAsSQ1aBPMEuAXzgDMoEEHADkAAQDOwAHZYANmmBQA9DA4kARhAAeIgNwAoA+WkT4qKDIDmAUQBuJaTACSROAF44NdQDoL1gAoASmMIU3MYS2krACUIIVc4Dy9ff2jg0PD8KKsAVQkSKETPb04-SMCQkzMvAGEwmEd4Et8AeQ0AKzIYAIRuIMMDEm1IWDg1Tjh7JoAeeqcmuGHG6QoJL3omFmSJkgg+OoamgD5k1AxsGYMkmJIYAFcoaVKSGd39qYcnOaOnY+ODMdDMNRvBqvBpk5kj8FlDlo41htGMw0McAvMVjAAFxwDFNIIeAFJF4+dpdLA9BDXJJwEyYnF4pw4alJXY4klpKy9Fk0qgSLCWMCYMJYnk0uAAIhoTHG6jgHxIXxgPi8DGA62QAAlWrkADJuDRcaRoEAkCRgNBYEgUOBSEDABRQcYQOAAKTQdjQcAtWAA1mgrEaTdZaWElcAwusSD4rCqROQQD5hiawHJoxJ7hoKEJFNIk0qfLsRBLmeL+qWeAMjCDoPBdnBcqZgFZpNaiBgvZ5zoQ3uoPo2pC22x2gUMRrXQ1kB83WxR2+hkiSyd1uUkAyR2W0hRHjXIAjySQA5e4gQ1QVfiuB8gXAbcisU0kTSriYU1wGRwe1yOTqshhREwAwGBwEBUYKGABQ2lIsgvjKiqLAA7mg6wFE4KrSuq-DACQcg2phgatlAGDWnAGhsOMMpyBAWBoHIIFCGahQOFAeBoKsn5oORhrvrI0BQN074HIBXBUTRdGvlwYRwMBabIfAYSSUJMowAhLoFFAzHrJhED3PJBwSGwsh4AhaqMLSbHmfcBQUVw67OkswDCU63GtlYFwOPKTpWPxxFOoBFmOdJFL3LRcjkeqPgiBW4p8NALDYqIMgwAAbAALFFD7JuAaY4gAjAArMlADsqUAMxFdFlbUkEFb8RQlqNBQAD6ho0VZG4pGUrR3ruAQko2vrSBACHSMENXUpEbESA1O5NcAFCbl1PW0fu4ochU6RUpeV5mjePWittSRPjK8jYU4AC0GZgKm2E2gA2pNpgzVJrgALoBMop1NJdTGFOdaBgMAygAMSPdNFI7ud81NMAfDYVAEg1fw0BLNoKZpngYCCHY0M2jjaAADrSAABgACrkNBwMoTXxZY2ifT+TTKHYpXKIIQgSMoCDsyAzgUNwyioRQXPwU4LwCwgMDaNIfPcMTOBE7DNm0ozUKGiGVjAF8yui-AmHCbaJqSa2cAmdgDC2osjk+ETGVliESTjUkWOKk1dJNIt0bdcKvX9dIg3DaNQTjf0gw1mM9bIIZWBxEIkIwDCmKoysiJ0Mi2yeO8Bw0IyMCnF2BCXNStwPE8Ly9pwHxR7IscgPHicnACo7h2CkbmNHtfx9CufJwi6xp1sqLor8CW5wS7hEp10bOAsCMrndPLx8PsIwE7NJLp0K5bZeutzQt2TWPHriVUkQuFDinL5IUx8PtAzYyE16nMU1MASJ7PjHqehQXtt16Cj7B1DpHRoKAM06BwA8U-A6H8BQTCIiknfTWxpMDRHoqaJ+hRTZMGkBRTCutTbIUtmhO2h1YpQHijiEQSU0okPtifOA9wmxDn3kuZae5pzMPnGgNeSRyzUlelWMcoJZSTE7kqBucJtAp37psFEOw+zZ1zvnfAFxiB-ioFcG4dxHjPHUBXPYBwxGzCUU3YE44xjgjgEYqEngJHwHhKsGR6ch65wZCPcek8SQz0aHPCkAQF7imrjHeIdclTL0xDwqepJN5+O3uKHme8L4bViCEm+dD+GCMsd2EgABpEg5EWhdRiZSakZhiJNV9Pk9+nIf47X5P-HcgDxQSgAIIMOkMAAAjvcLglTyJmzMlQOGrZ1gGwgMxBClgUFWEtiwJw2B1hkNwesQGZBFJwB5raAg0ZVSYU9HIHp751j7BWNJOAAAvQoEBzppmiIBLZOR0IyhdqhK08olKYT6RxSpoy1RRiVGc7Jnwmg22kECvpKF0CwBDAhRyFsLLEzEMTaS-ENmMQ0iRJZ-E+CFEcFgEM7UnSuAkHgDMZlCGbNNF-BGKoADqcKdbaCtD1d5ZycUISWEqElWziKcqaChO4psGVek1trQlIh1iJEIQbMpjQ4BfIALK5GQJTMIYVSJcAKPAMiFFgKEp8CWakfDQ7VnMXWOUQTsn1x7g41OsiM4iIMYcFe+dqTdmwKQcgGiS46PLlnFA0crXiJMc3M1k4aiWu2V3WxNqpF9yRIPNErjcTuMJNSLxs9YE9DukE6xPQx54GyXktgAiw5hsjlG4NI9e6OITXIzOCjnWYldUkd1aivWvB9WXPR-qg3GJHv8UNwismVsWDG6ttqnGJvCR7FNK8PHpt8N4woWb-F5pnU4JGRb8mltNcIitgpOAUD7TYlRhBPWUFeL2io11rQnrzmY4dbcD63uPaO09G9yQlKSO7Jw78BpDRGsECssqSAVKqVEmpSA-63gAaIZ8cBiagfA2wZFSyDa60ipWCsbJIPJN6HUvacHjpcGJrsNDKMMMFhENh0pCJz4H2iFfIoRBmQmoMEAA)

If you just want to test version 0.32.15 and let me know how that helps solve things, that would be great. I don't know if I'm going to be able to revert Composite back to a previous version (as the current implementation is closer the envisioned computed type), but do think there's potential to further optimize the type for the implementation you've provided. There is some pending work to do with respect to deep type evaluation (of which Composite would be involved), but I don't envision optimizations making it out until TypeBox reaches 0.33.x (which is a fair way off)

For now, give Intersect a try (which will keep you on the latest versions) and just let me know if you still run into issues on 0.32.15, I'll do some digging based on your feedback.

Cheers!
S

**Comment by Gnuxie** [comment] 2024-04-11 12:03
Hi, thanks for the speedy response, I'll see what happens in 0.32.15 and report back. 

> Workaround

For now though, I want to add some context for why I originally moved away from `Intersect`, and there are two reasons.

The first is it's less helpful dealing with the typescript union type when trying to debug an issue, since obviously they can become so massive. It can be very difficult to see what is wrong based on the output typescript gives when working with what are believed to be (by me) compatible types. And then VSCode would also expand references to types into a massive type literal when using VSCode's feature to add missing methods when implementing classes in interfaces, and I would get annoyed trying to delete them. Which yes, is probably a silly reason :sweat:.

e.g.

```
interface Timeline {
    addEvent(event: RoomEvent): void;
}
```

```
class StandardTimeline implements Timeline {
    addEvent(event: { ... }
        & { .... }
        & { .... }
    ) {
        throw new TypeError("Unimplemented");
    }
}
```

> However, the Composite evaluation is an extremely expensive thing to compute, and I think when tagged with ReturnType inference (instantiation expressions as per your implementation), this is likely pushing out the extents of the type system.

I see, I don't really understand how the type system works but I trust you. I'll follow up shortly

**Comment by Gnuxie** [comment] 2024-04-11 12:39
The problem seems to be introduced within `0.32.0`.

**Comment by dwickern** [comment] 2024-04-18 19:46
I'm seeing this issue starting in 0.32.9

**Comment by sinclairzx81** [comment] 2024-04-18 19:57
@dwickern Heya,

Hmmm, not sure if I'll be able to revert recent Composite functionality, ill have to try and optimize around it. Would it be possible for you share a repro of your type setup? (just wanting to take a look at some of the downstream use cases where Composite is popping out). Any info / reproduction you can provide will be helpful.

**Comment by Gnuxie** [comment] 2024-04-18 22:01
Just an update before anything goes further, i suspect that upgrading typescript can trigger the same problem in `0.31.*` but haven't investigated yet.

**Comment by sinclairzx81** [comment] 2024-04-19 04:56
@Gnuxie Hi,

So, I've dug a bit deeper into this issue using [this code](https://github.com/Gnuxie/matrix-protection-suite/blob/bfddf00c4adb3336a61ff52bd7bfb44d6698b5c8/src/MatrixTypes/Events.ts#L95) as a basis. I do think TypeBox has introduced a deep inference issue on 0.32.0 which I'm going to try and resolve through optimization, however resolving it is difficult as the inference is already quite optimized. 

Currently 0.32.0 inference / evaluation of Composite is correct and inline with TS evaluation, it's just that in order to replicate TS evaluation, the work TB needs to do is very top heavy (with this issue specifically seemingly only popping out on deep instantiation expression via ReturnType, although I've been able to push it out in a couple of other ways)

Ill spend some more time today looking for temporary solution, however I don't anticipate a fix will be possible on 0.32.0 as the inference infrastructure may require some refactoring (which would be more indicative of a 0.33.0 minor revision). As mentioned tho, you can swap from Composite to Intersect (which will produce the same inference (non-normalized) and a non-evaluated `allOf` schema representation). This may serve as a temporary workaround.

Will keep you posted
S

**Comment by sinclairzx81** [comment] 2024-04-20 21:56
@Gnuxie Hi,

So have investigated this issue further, and unfortunately I don't think I'm going to be able to resolve this on 0.32.x. As it stands, things are already as optimized as I can get them using the current inference strategy, and I think to go further, I'll need to investigate an alternative strategy which will take time (and a revision bump). 

As it stands, to solve this issue on the current revision would involve removing inference logic which would make Composite "less correct", it's just that correct-ness in this case has come at a instantiation depth cost....which is unfortunate.

---

### Revisiting Intersect (Workaround)

> The first is it's less helpful dealing with the typescript union type when trying to debug an issue, since obviously they can become so massive. It can be very difficult to see what is wrong based on the output typescript gives when working with what are believed to be (by me) compatible types. And then VSCode would also expand references to types into a massive type literal when using VSCode's feature to add missing methods when implementing classes in interfaces, and I would get annoyed trying to delete them. Which yes, is probably a silly reason 😓.

I do think it's reasonable to want presentable types! However I would encourage you to revisit Intersect as a workaround as there are options available to you to leverage Intersect while still obtaining flattened types. TypeBox does export a `Evaluate` utility type which performs a "static type level" evaluate (producing the same inference as Composite) on intersected and unioned types.

```typescript
import { Evaluate } from '@sinclair/typebox'

type T = Evaluate<{   // type T = { a: number, b: number }
  a: number
} & {
  b: number
}>
```
The following is an update to the provided reference issue code using Intersect + Evaluate to flatten out the types.
 
 [src/MatrixTypes/Events.ts (implemented with Intersect + Evaluate)](https://www.typescriptlang.org/play?&a=1#code/JYWwDg9gTgLgBAbzgZRgQxsAxgEQKZYQAmeANHACrJYAWeIa5FAnmGXAKIBuaANgK4Y8cAL5wAZlAgg4AcgACAZ2AA7LLzTAoAehis8AIwgAPWQG4AUBe3aUbLMD7AAXniIp0mLHAC0nHgJCinAAkioweFCKBJgQKsFowQDyBgBWMXB6bBZ4xpCwmfoeGNgAPBRwuREqRMFUtPRoAHxwALz+fIIRpagluATEeOVNTZbWthR00XAA7pHCoPkwihaE8fCoUKoA5tx44SE4bZT6AHSbOwAUAJSWa4obMFsq2wBKENKHxyxs509Xt1WcQeHme2wAqtEoF92j88H8wTcxjY4ABBYJsKBwQgkOBQPDieZqeGnU5A9aUADCcWq8FhZxS6SwMEuCBEgJyeWg8Cywj24VK1PC+3gVX2tUo1DoDGOvIg4ipNJFLXavS8pQscDgrzwMH4UBUcNKcoV-JggqV4RGFlGnKW2OB8DNxwtwvClWM1Ql9WlzUuQtpAC44AGRdc2k1NSdfoyYqyo1q1kGQ5aYKQE4U2MG4QirggM1qSIosFswLEVIGC1q4AAiSbCXlweWVLgi06UGjAYLIAASSXBABkjgZhCo0CA8IowGgsG44MoQMANFiYBA4AApNA8ODTrAAazQ21H452DpUrfCwGBlVO23bskIIFOuXHYF48MU-AMRGkmhUz4vGBTl5WQa3TatRGucDILGXJ7UbcF4mAbYVDcHAMDQY41TKE04EQ5QULQjDbTg7kzxBfDkNQoh0PQb4GTSON8y1Q88GzBkyyvMdeEuDMcwAOX4EARygeMIMLScS2ATi4krcTq1ketMlABYVDgRdeF4LsBhqYIYBoDA4AM4I8A0MBoncZRiUyOgWxFWZEnnNsOy7CRgFM9xXKPVCoCEdwDGYGzhF4CAsD4IzpEnSJWygcg0BqdS0ECkc4FUQgoHxZlUoVfTgtC8LMAnJs1MM99EngOJhGbXLMhmNcoRi4JXIgfgKoVRRmDUcgZk7WhsXi-r+GmGrWMyNc8GAXKsRS1DthKVsmyxbZ8SEFcDLUya4BnPU+F4QKu1OWRoIg8RoAYGBg1kVQYAANgAFiOqsX3Ad9gwARgAVhugB2O6AGZvuOyCoygqN8SIba3AAfRHMKhrY6N4SSGTuMuHNEL3FQIBmFQblBrUnnixRtq4qHgCIdiYxRvheIgnMLheMTxKLKSUbk+S5CU9R3PCHxPzAN93PcABtQn4hJuJQhwABdS5tG5kU+eiyIfDQMBgG0ABiMXieZLifHJkVgHEdyoigiRoA9V933IMApC4Q33AdtAAB0VAAAwABXBCptCh86tmMeWtJFbQuD+7QpGkRRtAQKOQBCIgRG0aIaljvBALhZOEBgYwVETkR3dIN3jaC7EQ-dEdT22YALzLjP7NcmriaKyrZl6mgnPdSbTjdx6IPZEHoLtjOoaTEVKaR6mePRlRMex3HrlB9lYK5ApG2QTqsHeaQzVdWkPS9OopUaWV9GbChQytLDPDKKMdT1A0jVwze1B3kA96vmBrRItf4HuDYW937OnaPveyYpdKSgaAwJo-pUzBi-uGVokYtQ5jCBEKIcZhYZjNHAt0MB8bVhzLGZkTMIIN3CGTCmoIdhmkOEDLUqcSBQGDAzCEUJ6FVmgMhVQUMGqRChssSepxBLCUiGQ5mklSzlnZhzTmKkHivlSmpDSWlohrAlJLbhNcxyYBeBFCc-CsQ9X2DZVyFD4AzEcqnIC-cOanSgOdS6117p2IHoQiC-AkKEWocQ6elxKI+NomgDxkFoLSw5KRdeRRgGATAe6CB3oT4ynaLhS+qYVTFHVPfXU+pDT6GNOfBUsSRTxO-pGX+9oAHag+B-QCLov6H3FMfaBfov4INTEglBiNTjoMiOolk2CIKv23rU3BiCgbEMYqQ5i4l45UNYf8F479OHuPCRyapao8AAGk8CBXpDGaZLJZmKIiFDPcezhFsIkSzaRXFZHVhrKiOAXjgAAEd+DCAuYFHq2BO4kBNqhPStkIAxRmFsPR2wnIMEvFgYIDizEYncrOJsCp47zk8PCFywQAifNSsEeU1QtpwFcFIHw74Xj6QxWCdsSkR6pxRdVTswRvmJQucC8x9TMJbP8G2N2PLvnBEUbAU8MxJqdwGu7eQ7str4jxFFKArZ3AIvxISfEahTzwyxIcRQ5BPx9UcuiicYiojtgAOrivrsYWcKNUXEsJDMOy4RdUYqEE65YTlLGWswjXOuWrZDBC+I5ZumK4CsoALLgmQBUOIe04ApWiPAAKNlDJatOGBKM7J0wrysFEnkRQRlbM-qmJpkCfSn1SUUxU+CVRRm4J0IQPRb79BxEMB+eTn5VsLZi4tNaRiVLIpsreRb6mgMaYklpvpYHtJTPgrpUY0HCkwaQ4WIySnhDwbSc2WzdnMAiaveCBae1xPHZ6ZpUDfRnzYBfL+tatTYSwKUdtT8Ckv2PaU29IxLB5vIo8IQIC4BlNLUk1p074Gzq3RGBdZw+nLsGeulkEysk7L2fu3Nf9MzCAuALNwI77KqmbYU69CpsNsCIHhq036MObP+Dh8j773QHKRkcpm49wjCIxljHGNxoKnLwOcy5PTrlIFudJGRnNbLuz4wJ5gMqEU1QsYdMJUZeRXKWdsVkcBRNswk8Id2vI5OWwU4BJTWaoxMMiIssEkJIicJzVYIAA)

This is probably the best option I can advise at this time until I get a chance to really dig in and restructure some of the internals to support deeper inference. The above would keep you on the newer versions of TB. The only other thing I can think of would be to keep to pre 0.32.x revisions until this issue is resolved on 0.33.x. In terms of timings, I'll be aiming for minor revision sometime around late June (tentative).

Hope this helps in the interim.
S

**Comment by Gnuxie** [comment] 2024-04-20 22:35
@sinclairzx81 Thank you so much for the follow up, that's ok! The `Intersect` + `Evaluate` solution looks perfect to me, and while I'm not in a hurry to upgrade to `0.32.x`, I will incorporate it when I can.

**Comment by Gnuxie** [comment] 2024-04-22 18:51
While not an issue, just an observation for who might be following along, a side effect from moving from `Intersect` to `Composite` is that you can get duplicate errors from `Value.Errors` when the intersect has duplicate schema for some properties.

**Comment by Gnuxie** [comment] 2024-05-04 17:20
@sinclairzx81 do you expect there to be any performance implications for the change from `Intersect` to `Composite`?

**Comment by sinclairzx81** [comment] 2024-05-04 18:37
@Gnuxie Hi,

I have just measured the Decode performance for Intersect and unfortunately, you can expect a bit of a performance hit there. You can run the following test locally which runs 100_000 Decode operations across Intersect and Composite (where Composite is just an Object)

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const I = Type.Intersect([
  Type.Object({ a: Type.Number(), b: Type.Number(), c: Type.Number() }),
  Type.Object({ d: Type.Number(), e: Type.Number(), f: Type.Number() }),
  Type.Object({ g: Type.Number(), h: Type.Number(), i: Type.Number() })
])
const C = Type.Composite([
  Type.Object({ a: Type.Number(), b: Type.Number(), c: Type.Number() }),
  Type.Object({ d: Type.Number(), e: Type.Number(), f: Type.Number() }),
  Type.Object({ g: Type.Number(), h: Type.Number(), i: Type.Number() })
])

const V = Value.Create(I)

console.time('intersect')
for(let i = 0; i < 100_000; i++) Value.Decode(I, V)
console.timeEnd('intersect')

console.time('composite')
for(let i = 0; i < 100_000; i++) Value.Decode(C, V)
console.timeEnd('composite')


// intersect: 3.425s     - 3 seconds
// composite: 139.097ms  - 0.15 seconds
```
Performance will vary depending on the number of intersected Objects you have as well as the number of properties per Object. The main bottleneck appears to be an internal `KeyOf` operation which reaches into the schematics to pull back a set of known keys from the Intersect. 

The internal operation is loosely doing the following.

```typescript
type T = (
  ({ a: 1 } & { b: 1 } & { c: 1 }) & 
  ({ d: 1 } & { e: 1 } & { f: 1 }) & 
  ({ g: 1 } & { h: 1 } & { i: 1 })
)

type K = keyof T // "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i"
                 //
                 // ^ this operation is slow
```
Note the above operation doesn't need to run in the case of Composite as the KeyOf operation is already computed when you create the Type. With Intersect however it's computed dynamically using the following. You can call it manually with the following.

```typescript
import { KeyOfPropertyKeys } from '@sinclair/typebox'

const I = Type.Intersect([
  Type.Object({ a: Type.Number(), b: Type.Number(), c: Type.Number() }),
  Type.Object({ d: Type.Number(), e: Type.Number(), f: Type.Number() }),
  Type.Object({ g: Type.Number(), h: Type.Number(), i: Type.Number() })
])

const K = KeyOfPropertyKeys(I) // const K = [
                               //   'a', 'b', 'c',
                               //   'd', 'e', 'f',
                               //   'g', 'h', 'i'
                               // ] // need to optimize this.
```

---

I may take a deeper look to see if there's something that can be done to optimize things here. I do note the Decode is using the KeyOf operator from Type.* but where Type.* may perform interior Clone operations to ensure type immutability. There may be potential to implement a fast path key resolver which avoids these clones which might yield faster results.

Just make sure you're on the latest versions of TB as there has been other recent optimizations done to both Decode and Encode. You will want to be on a version 0.32.25+. Recent optimization PR can be found https://github.com/sinclairzx81/typebox/pull/849.

Let me know how you go.
Cheers
S

**Comment by sinclairzx81** [comment] 2024-05-04 21:10
@Gnuxie Hiya,

Have pushed an update on 0.32.29 to optimize Intersect Encode and Decode. The bottleneck turned out to be a combination of both KeyOf and Index resolution. The update adds a faster path for these and get around 2x the performance. Test code below.

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const N = Type.Transform(Type.Number())
  .Decode(value => value)
  .Encode(value => value)

const I = Type.Intersect([
  Type.Object({ a: N, b: N, c: N }),
  Type.Object({ d: N, e: N, f: N }),
  Type.Object({ g: N, h: N, i: N })
])

const V = Value.Create(I)
const D = Value.Decode(I, V)
const L = 100_000

console.time('intersect-decode')
for(let i = 0; i < L; i++) Value.Decode(I, V)
console.timeEnd('intersect-decode')

console.time('intersect-encode')
for(let i = 0; i < L; i++) Value.Encode(I, D)
console.timeEnd('intersect-encode')

// before: 0.32.28
//
// intersect-decode: 3.541s
// intersect-encode: 3.483s
//
// after: 0.32.29
//
// intersect-decode: 1.509s
// intersect-encode: 1.369s
```
Additionally, I've added an optimization to skip running Encode/Decode passes if the schema does not contain a Transform. So avoiding using Transforms with Decode will get you another 2x performance bump. Test code below.

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const WithoutTransform = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

const WithTransform = Type.Mapped(Type.KeyOf(WithoutTransform), K => 
  Type.Transform(Type.Number())
    .Decode(value => value)
    .Encode(value => value))

const V = Value.Create(WithTransform)
const L = 1_000_000

console.time('WithoutTransform')
for(let i = 0; i < L; i++) Value.Decode(WithoutTransform, V)
console.timeEnd('WithoutTransform')

console.time('WithTransform')
for(let i = 0; i < L; i++) Value.Decode(WithTransform, V)
console.timeEnd('WithTransform')

// WithoutTransform: 316.402ms
// WithTransform: 657.822ms
```
Just keep in mind, Transforms do have compute overhead, so if you can avoid using them the faster things will go. You can still use Decode without Transforms and get pretty good performance (as above), but for the best possible performance, validation pipelines should rely on Check only (and just reject invalid data)

PR for the above optimizations can be found [here](https://github.com/sinclairzx81/typebox/pull/862).

Cheers

**Comment by Gnuxie** [comment] 2024-05-05 11:54
Hey @sinclairzx81 thanks for doing a deep dive on this one, you're a real one. For some further context, I updated TypeBox to `0.32.22` within [matrix-protection-suite](https://github.com/Gnuxie/matrix-protection-suite) as advised, but I  also changed all occurrences of `Composite` to use `Intersect`. This [commit can be found here](https://github.com/Gnuxie/matrix-protection-suite/commit/c8b26aed18229a9c0ecf5439394e160ebd005e5e). We use a [wrapper](https://github.com/Gnuxie/matrix-protection-suite/blob/main/src/Interface/Value.ts) around `Value` to call `Value.Compile` on the schema and cache those (which may be unnecessary?). Regardless, after updating typebox and making the change to `Intersect` we experienced a major performance regression in [Draupnir](https://github.com/the-draupnir-project/Draupnir) (the primary dependent of matrix-protection-suite). Basically we use the schema and our `Value.Decode` wrapper to decode thousands of objects fresh from `JSON.parse`when Draupnir starts. The difference in startup time was ~10seconds to just over a minute and I haven't been able to profile this specifically, so this is loose at best (I am [working separatly](https://github.com/the-draupnir-project/Draupnir/issues/389) to get into a position where I can reliably diagnose regressions like this in the future).

For next steps, I will update to `0.32.29` and let you know how that goes, I also acknowledge that you say version below`0.32.25` are expected to take a penalty so fingers crossed we should see an improvement. 

>Just keep in mind, Transforms do have compute overhead, so if you can avoid using them the faster things will go. You can still use Decode without Transforms and get pretty good performance (as above), but for the best possible performance, validation pipelines should rely on Check only (and just reject invalid data)

Yeah this is a good call. We only use transforms to "safely" trick typescript into type asserting custom string types, and on top of that there's no reason why we can't call `Value.Errors` after `Value.Check` has failed to get detailed information about the validation failure (we do that anyway if `Value.Decode` fails). So I will see about refactoring to use `Value.Check` instead.

Thank you again for all of your work and insight.

**Comment by sinclairzx81** [comment] 2024-05-05 17:33
@Gnuxie Hi, thanks for the follow up response...

---

> For some further context, I updated TypeBox to 0.32.22 within [matrix-protection-suite](https://github.com/Gnuxie/matrix-protection-suite) as advised, but I also changed all occurrences of Composite to use Intersect. This [commit can be found here](https://github.com/Gnuxie/matrix-protection-suite/commit/c8b26aed18229a9c0ecf5439394e160ebd005e5e). 

In terms of application start up, using Intersect should technically be faster (as Intersect types don't need to be computed), but as noted, Intersect decoding performance will be a bit less due to internal KeyOf / Index operations performed on Decode that are specific to Intersect. I suppose if running Decode ops as a prerequisite to start up, that could be a bottleneck....

Looking at the [commit](https://github.com/Gnuxie/matrix-protection-suite/commit/c8b26aed18229a9c0ecf5439394e160ebd005e5e) though, everything seems fine I wouldn't initially expect these updates to pop from 10second -> 1minute+. However I've run a quick performance benchmark across Composite and Intersect for Compile, Check, Decode. 

The following are the deltas for 100K iterations for each operation

<details>

<summary>Benchmark Reproduction Code</summary>

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type, TSchema } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

function Benchmark(name: string, iterations: number, schema: TSchema) {
  const check = TypeCompiler.Compile(schema)
  const value = Value.Create(schema)
  console.log(name)
  console.time(`check`)
  for(let i = 0; i < iterations; i++) Value.Check(schema, value)
  console.timeEnd(`check`)
  console.time(`decode`)
  for(let i = 0; i < iterations; i++) Value.Decode(schema, value)
  console.timeEnd(`decode`)
  console.time(`compile`)
  for(let i = 0; i < iterations; i++) TypeCompiler.Compile(I)
  console.timeEnd(`compile`)
  console.time(`compile-check`)
  for(let i = 0; i < iterations; i++) check.Check(value)
  console.timeEnd(`compile-check`)
  console.time(`compile-decode`)
  for(let i = 0; i < iterations; i++) check.Decode(value)
  console.timeEnd(`compile-decode`)
  console.log()
}

const N = Type.Transform(Type.Number())
  .Decode(value => value)
  .Encode(value => value)

const I = Type.Intersect([
  Type.Object({ a: N, b: N, c: N }),
  Type.Object({ d: N, e: N, f: N }),
  Type.Object({ g: N, h: N, i: N })
])
const C = Type.Composite([
  Type.Object({ a: N, b: N, c: N }),
  Type.Object({ d: N, e: N, f: N }),
  Type.Object({ g: N, h: N, i: N })
])

const iterations = 100_000
Benchmark('intersect', iterations, I)
Benchmark('composite', iterations, C)
```

</details>

```typescript
// intersect
// check: 55.016ms
// decode: 1.581s
// compile: 1.146s
// compile-check: 3.56ms
// compile-decode: 1.510s

// composite
// check: 49.852ms
// decode: 152.714ms
// compile: 1.053s
// compile-check: 2.77ms
// compile-decode: 83.66ms
```

I do note the big jump from `83 ms` (Composite) to `1.5 seconds` (Intersect) for `compile-decode` (15x slower). This would be representative of the KeyOf / Index mentioned earlier. I don't think I'll be able to optimize the Intersect Decode more than it currently is (on this revision), so if you need maximum performance, it may be good to explore ways to remove embedded Transforms (i.e. string types) as running Decode for them may be prohibitively expensive in the case of Intersect.

> We use a [wrapper](https://github.com/Gnuxie/matrix-protection-suite/blob/main/src/Interface/Value.ts) around Value to call Value.Compile on the schema and cache those (which may be unnecessary?). Regardless, after updating typebox and making the change to Intersect we experienced a major performance regression in [Draupnir](https://github.com/the-draupnir-project/Draupnir) (the primary dependent of matrix-protection-suite). Basically we use the schema and our Value.Decode wrapper to decode thousands of objects fresh from JSON.parsewhen Draupnir starts.

I think the wrapper should be fine. Although caching compiled types can run risk cache misses (where the JS reference to the same schema changes (i.e. on clone) which might be a consideration if you don't know how Draupnir is passing types). Looking at the benchmark deltas though, even for 100K iterations (no cache), Compile + Decode should only be a couple of seconds.

> Yeah this is a good call. We only use transforms to "safely" trick typescript into type asserting custom string types, and on top of that there's no reason why we can't call Value.Errors after Value.Check has failed to get detailed information about the validation failure (we do that anyway if Value.Decode fails). So I will see about refactoring to use Value.Check instead.

Looking at the implementation for `StringUserId` it might be better to use the FormatRegistry (Check) + Unsafe (Brand). The following reimplements this type using the FormatRegistry where the branded type is handled by wrapping a String in Unsafe. This should be maximally fast as it avoids Transforms entirely.

```typescript
import { Type, FormatRegistry } from '@sinclair/typebox'

const UserIDSecret = Symbol('StringUserID')

// ... StringUserID 

FormatRegistry.Set('StringUserId', string => /^@[\S^:]*:\S*$/.test(string))

type StringUserID = string & { [UserIDSecret]: true }

const StringUserID = () => Type.Unsafe<StringUserID>(Type.String({ format: 'StringUserId' }))

// ...

import { Value } from '@sinclair/typebox/value'

Value.Check(StringUserID(), '@1234:5678') // true

Value.Check(StringUserID(), '@12345678') // false
```
Replacing all String instances with the above would give the fastest possible Decode (as the Transforms would never be run). If using Transforms for similar checks at the type level you can implement a similar strategy using the TypeRegistry. You can find a bit of information on these registries at the link below.

https://github.com/sinclairzx81/typebox#typeregistry

Let me know if this helps
Cheers
S

**Comment by Gnuxie** [comment] 2024-05-06 13:06
Hi again, I updated to `0.32.29` and followed your advice for changing the various `Transform`s to use the `FormatRegistry` and `Type.Unsafe` instead.

That seems to have gotten us roughly back to the same startup time we had before this saga began :tada:.

Thanks once again for all of your help!

**Comment by aadito123** [comment] 2024-06-03 02:09
For those who cannot move to Type.Intersect from Type.Composite, I would recommend doing a cast so that inference can be short-circuited. It can remain type-safe with the following snippet.

```typescript
const $assertType = <
  Cast extends TSchema,
  Target extends TSchema = TSchema,
>(
  t: Target,
): Static<Cast> extends Static<Target> ? Cast : { ERRORRRRRR: 'Invalid cast' } => {
  return t as any;
};

type MergeTObjects<T1 extends TObject, T2 extends TObject> = TObject<
  T1['properties'] & T2['properties']
>;

// wont get the "inference too deep" error
const schema = $assertType<MergeTObjects<typeof schema1, typeof schema2>>(T.Composite([schema1, schema2]))
```

The above is directly inspired by [Kysely](https://kysely.dev/docs/recipes/excessively-deep-types), a query building library. @sinclairzx81 would it make sense to make this part of the library, as a property of TObject?

**Comment by sinclairzx81** [comment] 2024-09-02 22:38
@Gnuxie Hiya,

Might close off this issue for now as there isn't too much to action here. Note, I have recently done some work to improve schema runtime generation performance so if you grab the latest versions, you should see a significant improvement there. 

As for Composite inference / issues, I'm still looking for ways to optimize this through the type system (which I think is possible, but requires overhauling quite a few dependent types, Index, KeyOf, and various internal mapping types) but will likely implement this inline with a minor / significant revision (as these optimizations may require some large changes to TypeBox current inference strategy)

Will close this one out for now, but happy to field any additional follow up questions / discussions.

All the best!
S

**Closed by sinclairzx81** 2024-09-02 22:38 UTC
Labels: investigate, todo
