### ISSUE TITLE
Regression in 0.26.0 Type.Intersect

### ISSUE THREAD

**Issue by daffl** [sinclairzx81/typebox#373] opened 2023-04-10 18:09 UTC
This might be related to https://github.com/sinclairzx81/typebox/issues/364. The following schema:

```ts
const testSchema = Type.Intersect([
  Type.Object(
    {
      name: Type.Optional(Type.String())
    },
    { additionalProperties: false }
  ),
  Type.Object({
    port: Type.Number()
  })
])

// Same issue for this schema
const testSchema = Type.Intersect([
  Type.Partial(
    Type.Object(
      {
        name: Type.String()
      },
      { additionalProperties: false }
    )
  ),
  Type.Object({
    port: Type.Number()
  })
])

const validator = new Ajv().compile(testSchema)
const validated = await validator({
  port: 3030
})
```

Produces this JSON schema in 0.26.8:

```json
{
  "type": "object",
  "allOf": [
    {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "port": {
          "type": "number"
        }
      },
      "required": [
        "port"
      ]
    }
  ]
}
```

Which errors with 

```js
[
  {
    instancePath: '',
    schemaPath: '#/allOf/0/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'port' },
    message: 'must NOT have additional properties'
  }
]
```

And this JSON schema in 0.25.x

```json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "port": {
      "type": "number"
    }
  },
  "required": [
    "port"
  ]
}
```

Which passes validation.

**Comment by sinclairzx81** [comment] 2023-04-10 19:27
@daffl Hi

I'm not sure I can resolve this in TypeBox as the issue is caused by the `additionalProperties: false` constraint being applied to one of the sub schemas of `allOf`.  In previous versions of TypeBox (a very long time ago), I had attempted to solve for this case specifically, however attempts to do so resulted in a lot of complications as solving involved changing the semantics of one of the composite schemas (in this case removing additionalProperties constraint on `anyOf[0]`). 

The recommended solution is to avoid constraining schematics until they are fully composed (in which case you would apply a `unevaluatedProperties` constraint to the `allOf`).  This would look as follows.

```typescript
const testSchema = Type.Intersect([
  Type.Object({ name: Type.Optional(Type.String()) }), // remove additionalProperties here
  Type.Object({ port: Type.Number() })
], { unevaluatedProperties: false }) // add unevaluatedProperties
```

Information on this aspect on JSON Schema can be found at the following link https://json-schema.org/understanding-json-schema/reference/object.html#extending-closed-schemas. 

### Work Around

While it may not be possible to apply a general fix for this in TypeBox, you can implement the intended composition manually by remapping the constraints in the following way. See the `Fix` function below where I've made a guess as to what a default constraint remap could be, but the finer details of which you may need to contrast with other requirements. Also note that `unevaluatedProperties` requires `ajv/dist/2019`. 

Full example below.

```typescript
import Ajv from 'ajv/dist/2019'
import { Type, TIntersect, TObject } from '@sinclair/typebox'

// ----------------------------------------------------------------------------------
// Fix: additionalProperties to unevaluatedProperties
// ----------------------------------------------------------------------------------
function Fix<T extends TIntersect<TObject[]>>(intersect: T): T {
  const constrained = intersect.allOf.some(object => object.additionalProperties === false)
  if (!constrained) return intersect // if not constrained, just return as is
  intersect.allOf = intersect.allOf.map(object => {
    const { additionalProperties: _, ...rest } = object
    return rest
  })
  return { ...intersect, unevaluatedProperties: false }
}
// ----------------------------------------------------------------------------------
// Schemas
// ----------------------------------------------------------------------------------
const A = Type.Intersect([
  Type.Object({
    name: Type.Optional(Type.String())
  },{ 
    additionalProperties: false 
  }),
  Type.Object({
    port: Type.Number()
  })
])
const B = Type.Intersect([
  Type.Partial(Type.Object({
    name: Type.String()
  }, {
    additionalProperties: false
  })),
  Type.Object({
    port: Type.Number()
  })
])
const C = Fix(A) // fixed!
const D = Fix(B) // fixed!
// ---------------------------------------------------------------
// Test
// ---------------------------------------------------------------
const validateA = new Ajv().compile(A)
const validateB = new Ajv().compile(B)
const validateC = new Ajv().compile(C)
const validateD = new Ajv().compile(D)
console.log(validateA({ port: 3030 }), validateA.errors) // 'must NOT have additional properties'
console.log(validateB({ port: 3030 }), validateB.errors) // 'must NOT have additional properties'
console.log(validateC({ port: 3030 }), validateC.errors) // ok
console.log(validateD({ port: 3030 }), validateD.errors) // ok
```
Let me know if this helps
Cheers
S

**Comment by sinclairzx81** [comment] 2023-04-10 20:36
@daffl Just submitting extended type builder example here for review.

```typescript
import { ExtendedTypeBuilder, TypeGuard, TObject, TIntersect, TNever, Kind, TSchema, Static, SchemaOptions, IntersectOptions } from '@sinclair/typebox'
 
// ----------------------------------------------------------------
// Implements the 0.25.0 fallback for Intersect types.
// ----------------------------------------------------------------
export class FeathersTypeBuilder extends ExtendedTypeBuilder {
  /** `[Standard]` Creates a Intersect type */
  public Intersect(allOf: [], options?: SchemaOptions): TNever
  /** `[Standard]` Creates a Intersect type */
  public Intersect<T extends [TObject]>(allOf: [...T], options?: SchemaOptions): T[0]
  // /** `[Standard]` Creates a Intersect type */
  public Intersect<T extends TObject[]>(allOf: [...T], options?: IntersectOptions): TIntersect<T>
  public Intersect(allOf: TObject[], options: IntersectOptions = {}) {
    const [required, optional] = [new Set<string>(), new Set<string>()]
    for (const object of allOf) {
      for (const [key, property] of Object.entries(object.properties)) {
        if (TypeGuard.TOptional(property) || TypeGuard.TReadonlyOptional(property)) optional.add(key)
      }
    }
    for (const object of allOf) {
      for (const key of Object.keys(object.properties)) {
        if (!optional.has(key)) required.add(key)
      }
    }
    const properties = {} as Record<string, any>
    for (const object of allOf) {
      for (const [key, schema] of Object.entries(object.properties)) {
        properties[key] = properties[key] === undefined ? schema : { [Kind]: 'Union', anyOf: [properties[key], { ...schema }] }
      }
    }
    if (required.size > 0) {
      return { ...options, [Kind]: 'Object', type: 'object', properties, required: [...required] } as any
    } else {
      return { ...options, [Kind]: 'Object', type: 'object', properties } as any
    }
  }
}
 
export const Type = new FeathersTypeBuilder() // re-export
 
// ---------------------------------------------------------------------
// Example
// ---------------------------------------------------------------------
 
type T = Static<typeof T>
const T = Type.Intersect([
  Type.Object({ name: Type.Optional(Type.String()) },{ additionalProperties: false }),
  Type.Object({ port: Type.Number() }),
])
 
// const T = {
//   type: 'object',
//   required: ['port'],
//   properties: {
//     name: { type: 'string' },
//     port: { type: 'number' }
//   }
// }
```

**Closed** 2023-04-12 17:20 UTC
