### ISSUE TITLE
The inferred type of 'X' cannot be named without a reference to '@sinclair/typebox/build/import/type/static/static.mjs'

### ISSUE THREAD

**Issue by antmarot** [sinclairzx81/typebox#722] opened 2024-01-09 10:04 UTC
After upgrading to `0.32.5` from `0.31.28` I'm getting a new typescript error.
Looking at the breaking changes in the release notes did not help me identify what could be the cause.

Consider this trimmed down version of my code:

```typescript
import { Type } from '@sinclair/typebox';

import type { StaticDecode, TSchema } from '@sinclair/typebox';

type EnvSpec = Record<Uppercase<string>, TSchema>;

const schemaFromSpec = <T extends EnvSpec>(spec: T) =>
  Type.Partial(Type.Object(spec));

type EnvType<T extends EnvSpec> = StaticDecode<
  ReturnType<typeof schemaFromSpec<T>>
>;

export const envLoaderFactory =
  <T extends EnvSpec>(spec: T) =>
  (): EnvType<T> => {
    // originally there was some Value.Check and Value.Decode here but they do not impact the issue
    return null as any; // not relevant to the issue
  };
```

No TS errors with `0.31.28`.

With `0.32.5` I'm getting this error:

```
The inferred type of 'envLoaderFactory' cannot be named without a reference to '../../../node_modules/@sinclair/typebox/build/import/type/static/static.mjs'. This is likely not portable. A type annotation is necessary.ts(2742)
```

Typescript: `5.3.3`
NodeJS: `v20.10.0`
package.json: `"type": "module"`
tsconfig.json:
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "declaration": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "strict": true,
    "types": ["vitest/globals"]
  }
}
```

**Comment by sinclairzx81** [comment] 2024-01-09 12:48
@antmarot Hiya

This looks like a TypeScript quirk with immediate instantiated return types given through currying. You should be able to resolve this by converting `envLoaderFactory` into a function that explicitly returns the interior function. See below

```typescript
import { Type } from '@sinclair/typebox';

import type { StaticDecode, TSchema } from '@sinclair/typebox';

type EnvSpec = Record<Uppercase<string>, TSchema>;

const schemaFromSpec = <T extends EnvSpec>(spec: T) =>
  Type.Partial(Type.Object(spec));

type EnvType<T extends EnvSpec> = StaticDecode<
  ReturnType<typeof schemaFromSpec<T>>
>;

// Update: Remove arrow function currying. This appears to help TypeScript statically resolve the return signature
export function envLoaderFactory<T extends EnvSpec>(spec: T) {
  return function (): EnvType<T> { 
    return null as any
  }
}

// ---------------------------------------------------------------------
// Test
// ---------------------------------------------------------------------
const A = envLoaderFactory({
  NAME: Type.String()
})

const B = A()
```
Give the above a try, and let me know if this helps

**Comment by tylerc** [comment] 2024-01-09 19:17
@sinclairzx81 I'm encountering this error on `0.32.5` with a much simpler setup:

`exporter.ts`:

```ts
import { Type } from "@sinclair/typebox";

export const TestExport = Type.TemplateLiteral("test_${string}");
```

`package.json`:

```json
{
  "name": "minimal",
  "scripts": {
    "dev": "tsc"
  },
  "license": "MIT",
  "dependencies": {
    "@sinclair/typebox": "^0.32.5",
    "typescript": "^5.3.3"
  }
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "node16",
    "moduleResolution": "node16",
    "declaration": true
  }
}
```

Running `tsc` yields:

```
exporter.ts:3:14 - error TS2742: The inferred type of 'TestExport' cannot be named without a reference to './no
de_modules/@sinclair/typebox/build/require/type/template-literal'. This is likely not portable. A type annotati
on is necessary.

3 export const TestExport = Type.TemplateLiteral("test_${string}");
               ~~~~~~~~~~


Found 1 error in exporter.ts:3
```

In version `0.31.28` this compiles without error.

**Comment by sinclairzx81** [comment] 2024-01-09 23:18
@tylerc Hi, thanks for reporting. Yes, I'll take a deeper look into this. 

Both issues appear related to `declaration: true`, TypeBox ESM and updates made on 0.32.0 to only export public type infrastructure. I think in the `TemplateLiteral` case, the issue may be somewhat different to the first issue in that TypeBox isn't exporting enough of the supporting type infrastructure (specifically TTemplateSyntax in this case)

I'll take a look and report back on this thread.
Cheers

**Comment by sinclairzx81** [comment] 2024-01-10 04:07
@antmarot @tylerc Hiya,

Have pushed a fix for this on 0.32.6. This issue appeared to be caused by TypeBox not exporting enough of the inference infrastructure on 0.32.0 (as there were efforts to reduce the API surface area of TypeBox in this revision). 

It's noted that exported user defined generic TB types will cause TypeScript to synthesize the type in `.d.ts` files if the inference infrastructure is non-public. This was causing both "cannot be named without reference" errors as well as declaration emit lengths exceeding limits in some cases (which was interesting for the Mapped case)

I have made updates across all "mapping" types to export dependent inference infrastructure which should solve the problem.

If you can give this revision a quick test, can close off this issue.
Cheers
S

**Comment by antmarot** [comment] 2024-01-10 08:50
@sinclairzx81

I confirm `0.32.6` fixes all issues on my end 👍 
Thank you for the amazing support!

I let you close this ticket in case you prefer to wait for confirmation from @tylerc as well.

**Comment by tylerc** [comment] 2024-01-10 14:39
Thank you for the quick fix @sinclairzx81! I really appreciate it.

I can confirm that the minimal example I posted above no longer has errors with the latest version, and the project I originally encountered the error in no longer has errors either 🎉

**Closed** 2024-01-10 15:12 UTC
