### ISSUE TITLE
Date object validation results in 'Ajv 'unknown keyword: "instanceOf"' error

### ISSUE THREAD

**Issue by RussBaz** [sinclairzx81/typebox#462] opened 2023-06-12 13:36 UTC
Hi. If I follow the provided instructions for working with Ajv while validating the Date object, I am getting `Error: strict mode: unknown keyword: "instanceOf"` error.

Here is a reproduction repo I prepared: https://github.com/RussBaz/TypeBoxBugSubmission

Am I missing some configurations, or is this a bug?

Thank you.

**Comment by sinclairzx81** [comment] 2023-06-13 04:36
@RussBaz Hi,

Not a bug. You will need to check with the Ajv documentation for adding these extension types and keywords as `Date` objects are unpresentable in JSON Schema. The `instanceOf` property is a non-standard schema property (as you've seen), but is used specifically as a hook-able keyword for Ajv, but you will need to configure for it (Note that Ajv configuration is above and beyond the scope of TypeBox)

Formal documentation for adding custom types + keywords to Ajv can be found [here](https://ajv.js.org/keywords.html)

### Example

The following is a quick example of setting Ajv up to work with `Date` and `Uint8Array` buffers (both of which are above and beyond the JSON schema specification). The main thing is registering the `instanceOf` keyword to validate via the `schemaOf` function. The rest of the configuration is just adding known constraints for `Date` and `Uint8Array` (Ajv requires you explicitly opt into known keywords or it will throw strict errors as you've seen).

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgNQIYBsCuBTOBfOAMyghDgHIABAZ2ADsBjdVYKAehgE8xsAjCAB5sAbhhzkAsAChQkWIjgAVbtgA0SlQHFMqKABN8REmSq1GzVhxX8BkmeGjxUevQDFoIVDGpHSFVABWwgC0hB5e1HayjnAAgkG+JoHCdtKEmIwwwBB0cNQMABbYngDyhAAU+UWlhABceTBQ9ADm6qJY2PUZANZ0EADudOpVxahddL0DdACUiNJwef3AMIVwlYWjZbMI8wtwDKjUuOQAIl7Y5LW7e3BQ2DCYULnKPNq6egB0imcw2OvVqFmADIgSgxNgPgBhIoMbr-UZtcHTa77Q7HACq9BgAA5YlAoKhOJcUQs7g8nhpXjp9F9MXQcXiCZx4Z5gaC0B0oTC4SNPIiOsipDc9NhCKhMOgYPUSbd7o9cmL0Ec4Gw2HA+vBqJgwHJfnpdnhpIapNJsAJdfsctR4Aw7ud4sI4ABeNazJ0APjgzjc4W85To2H6cSC5QQeGm6gA2ijyHpzsEsiALuoY4nk3AY3HfuQU0K9uRRsB0DmFjGChBrXRUEmSzHgGBhAAWWt5hbkevCABsLZu5EewB7+f7wTuhGwd0Y6ZjmEwwD0OenTQTxTAzGzud7AWoOWCkCx48Hbbua+AwmwwS3O739IPG-zd2aZrsCwAuoKFh9vQBpbCcfrQPRQzgLgeHqcgIF4AJsAYGAS26X9-30MD6GtVBJzKEt2jnc56l5VAynwd84E-Fwfz-ADygLAQmEwWgzwAWXoUBMBARRQGwVDwHIIiSL0MjEMAqiaLo7B6NQARmNY9jOLAbjdl4-iKPIEAmJAFi2KTGS5LzBSEKUzwJLUqTNJgatZJ4789P0SiVLoAAhThfgAGWwOhmhgAptI-SzyOs5TxIc5zXPczzBWkaQGCtJwEhdW1sHtEMwqkSK6GtOAACVnS9IIPiwrM-heCESkg6CYFDXZeEwQgxygepCo+OkGXxQlygjXZ8rqlQPh+P42qkcN1B2PNKuq8d6gDINGtxZrmT6hYOvVQM4B61rVCNJKUu3dAIXQCBmnKdLpiAA)

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type, TypeGuard } from '@sinclair/typebox'
import addFormats from 'ajv-formats'
import Ajv from 'ajv'

function schemaOf(schemaOf: string, value: unknown, schema: unknown) {
  switch (schemaOf) {
    case 'Date':
      return TypeGuard.TDate(schema) && Value.Check(schema, value)
    case 'Uint8Array':
      return TypeGuard.TUint8Array(schema) && Value.Check(schema, value)
    default: 
      return false // not supported
  }
}

export const createAjv = () => addFormats(new Ajv({}), [
    'date-time', 
    'time', 
    'date', 
    'email',  
    'hostname', 
    'ipv4', 
    'ipv6', 
    'uri', 
    'uri-reference', 
    'uuid',
    'uri-template', 
    'json-pointer', 
    'relative-json-pointer', 
    'regex'
  ])
  .addKeyword({ type: 'object', keyword: 'instanceOf', validate: schemaOf })
  .addKeyword('exclusiveMinimumTimestamp')
  .addKeyword('exclusiveMaximumTimestamp')
  .addKeyword('minimumTimestamp')
  .addKeyword('maximumTimestamp')
  .addKeyword('minByteLength')
  .addKeyword('maxByteLength')


const ajv = createAjv()

const R = ajv.validate(Type.Object({
  buffer: Type.Uint8Array(),
  date: Type.Date(),
}), {
  buffer: new Uint8Array(),
  date: new Date(),
})

console.log(R)
```
Hope this helps
S

**Comment by sinclairzx81** [comment] 2023-06-14 05:41
@RussBaz Hi

Will close this one off for now. You should be able to configure Ajv with the example code above (the `instanceOf` and `typeOf` non-standard properties are included on the extended types as hooks for Ajv), however mileage may vary depending on the type. Uint8Array and Date should work well tho.

Happy to discuss more if you have have any follow on questions. 
Cheers
S

**Closed by sinclairzx81** 2023-06-14 05:41 UTC

**Comment by jrdnull** [comment] 2023-08-29 09:36
@sinclairzx81 what is the proper way to do this now, I am unable to find an example as mentioned in the changelog:
https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md#extended-type-representation-change

**Comment by sinclairzx81** [comment] 2023-08-29 09:52
@jrdnull Hi, sorry, I may have forgotten to implement this (will make a note to add an example over the weekend)

Since the 0.30.0 representation change, you will need to use `Type.Unsafe` type to represent custom Ajv types. The following implements the Date type using the pre-0.30.0 representation.

```typescript
import Ajv from 'ajv'

// ---------------------------------------------------------------
// Ajv Validation Function
// ---------------------------------------------------------------
function validate(schemaOf: string, value: unknown, schema: any) {
  switch (schemaOf) {
    case 'Date': return value instanceof Date
    default: return false
  }
}

// ---------------------------------------------------------------
// Date Fallback Type (Unsafe)
// ---------------------------------------------------------------
const AjvDate = () => Type.Unsafe<Date>({ type: 'object', instanceOf: 'Date' })

// ---------------------------------------------------------------
// Tests
// ---------------------------------------------------------------
const ajv = new Ajv().addKeyword({ type: 'object', keyword: 'instanceOf', validate })
ajv.validate(AjvDate(), new Date())    // true
ajv.validate(AjvDate(), 1)             // false

```
Hope this helps
S
